### ISSUE TITLE
Flapdoodle is not working with Springboot 3

### ISSUE THREAD

**Issue by SunnySourabh** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#19]
Hi,
I am getting error while using flapdoodle with springboot version 3. Details are mentioned below:

**Springboot version -** 3.0.2
**Java -** jdk17
**pom dependency for flapdoodle -** 
       `dependency`
            `groupId`de.flapdoodle.embed`/groupId`
            `artifactId`de.flapdoodle.embed.mongo.spring30x`/artifactId`
            `version`4.5.2`/version`
            `scope`test`/scope`
        `/dependency`
**application.properties -** 
        de.flapdoodle.mongodb.embedded.version=5.0.2

**Error -** 
[FlapdoodleError.txt](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/files/10953867/FlapdoodleError.txt)

I even tried to download mongodb-windows-x86_64-5.0.2.zip file manually and kept under .embedmongo/win32 folder but still didn't work for me.

Could anyone help me on this please? Thanks in advance.

**Comment by michaelmosmann** [comment]
@SunnySourabh are you working behind a proxy?

the latest version of flapdoodle mongodb stores downloaded artifacts different .. so just copy something into a win32 folder does not work anymore..

**Comment by SunnySourabh** [comment]
> michaelmosmann

Yes, I am working behind proxy. But I am getting same error when proxy is off.
When I was working with Springboot version 2 with flapdoodle dependency as 
**<dependency>
            <groupId>de.flapdoodle.embed</groupId>
            <artifactId>de.flapdoodle.embed.mongo</artifactId>
            <version>3.4.3</version>
            <scope>test</scope>
        </dependency>**
it was working by keeping flapdoodle zip fie under win32 folder.
**What is the way to work with flapdoodle in Springboot version 3?**

**Comment by michaelmosmann** [comment]
@SunnySourabh can you build this project? https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.canary

**Comment by SunnySourabh** [comment]
@michaelmosmann 
**I am trying to build the given project but build is getting failed with error:**
[INFO] Embedded Spring Boot 2.6.x Canary 1.0-SNAPSHOT ..... SUCCESS [ 17.481 s]
[INFO] Embedded Spring Boot 2.7.x Canary 1.0-SNAPSHOT ..... SUCCESS [  6.937 s]
[INFO] Embedded Spring Boot 3.0.x Canary 1.0-SNAPSHOT ..... FAILURE [  1.313 s]
[INFO] Flapdoodle Embedded MongoDB Canary Project 1.0.0-SNAPSHOT SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  28.354 s
[INFO] Finished at: 2023-03-13T14:18:06+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-toolchains-plugin:3.0.0:toolchain (default) on project de.flapdoodle.embed.mongo.canary.embed-spring-boot-30: Cannot find matching toolchain definitions for the following toolchain types:
[ERROR] jdk [ version='[17,)' ]
[ERROR] Please make sure you define the required toolchains in your ~/.m2/toolchains.xml file.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :de.flapdoodle.embed.mongo.canary.embed-spring-boot-30

Process finished with exit code 1



**Also I am getting error while running command - ./mvnw verify -Dembedded.mongo.version=4.5.1**
 ./mvnw verify -Dembedded.mongo.version=4.5.1
Couldn't find "C:\Users\C87033B\Downloads\de.flapdoodle.embed.mongo.canary-main\de.flapdoodle.embed.mongo.canary-main\.mvn\wrapper\maven-wrapper.jar", downloading it ...
Downloading from: "https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.4.2/maven-wrapper-0.4.2.jar"
Finished downloading "C:\Users\C87033B\Downloads\de.flapdoodle.embed.mongo.canary-main\de.flapdoodle.embed.mongo.canary-main\.mvn\wrapper\maven-wrapper.jar"
Exception in thread "main" java.net.ConnectException: Connection timed out: connect
        at java.base/sun.nio.ch.Net.connect0(Native Method)                        
        at java.base/sun.nio.ch.Net.connect(Net.java:579)                          
        at java.base/sun.nio.ch.Net.connect(Net.java:568)                          
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)      
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)    
        at java.base/java.net.Socket.connect(Socket.java:633)                      
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)

Also under my .embedmongo folder 2 subfolders are getting created automatically which are - archives and fileSets. 
**The same folder structure was also being created from my own project. But the download is getting failed. What is the new way to use flapdoodle in springboot 3? If download is failing, what to do in such case?**

**Comment by michaelmosmann** [comment]
@SunnySourabh there are only minor differences between the spring 2.7.x and spring 3.0.x integration .. and if i understand this correctly:
```
[INFO] Embedded Spring Boot 2.6.x Canary 1.0-SNAPSHOT ..... SUCCESS [ 17.481 s]
[INFO] Embedded Spring Boot 2.7.x Canary 1.0-SNAPSHOT ..... SUCCESS [ 6.937 s]
```
the tests with spring 2.6.x and 2.7.x succeed (and spring 3.0.x failed because of the maven-toolchains-plugin .. you can just delete this)

Is this right? If so, you can change the mongodb version in application.properties to 5.0.2 .. 

Are you using some kind of firewall? It is strange that you get a connection timeout as this is plain jdk stuff and no custom code..

**Comment by SunnySourabh** [comment]
> @SunnySourabh there are only minor differences between the spring 2.7.x and spring 3.0.x integration .. and if i understand this correctly:
> 
> ```
> [INFO] Embedded Spring Boot 2.6.x Canary 1.0-SNAPSHOT ..... SUCCESS [ 17.481 s]
> [INFO] Embedded Spring Boot 2.7.x Canary 1.0-SNAPSHOT ..... SUCCESS [ 6.937 s]
> ```
> 
> the tests with spring 2.6.x and 2.7.x succeed (and spring 3.0.x failed because of the maven-toolchains-plugin .. you can just delete this)
> 
> Is this right? If so, you can change the mongodb version in application.properties to 5.0.2 ..
> 
> Are you using some kind of firewall? It is strange that you get a connection timeout as this is plain jdk stuff and no custom code..

@michaelmosmann 
**Build is still getting failed even after deleting spring 30x.**
[INFO] Embedded Spring Boot 2.6.x Canary 1.0-SNAPSHOT ..... SUCCESS [ 17.224 s]
[INFO] Embedded Spring Boot 2.7.x Canary 1.0-SNAPSHOT ..... SUCCESS [  5.101 s]
[INFO] Flapdoodle Embedded MongoDB Canary Project 1.0.0-SNAPSHOT FAILURE [  0.396 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  23.973 s
[INFO] Finished at: 2023-03-13T15:32:11+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-toolchains-plugin:3.0.0:toolchain (default) on project de.flapdoodle.embed.mongo.canary: Cannot find matching toolchain definitions for the following toolchain types:
[ERROR] jdk [ version='[1.8,)' ]
[ERROR] Please make sure you define the required toolchains in your ~/.m2/toolchains.xml file.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**I checked in Control Panel -> System and Security and We are not using any firewall**

**Comment by michaelmosmann** [comment]
@SunnySourabh ah .. i think you can delete maven-toolchains-plugin in all pom.xml files.. 

and this test should work, if there is no issue with the network connection:

```
    @Test
    public void justCheckIfConnectionIsPossible() throws IOException {
        URL url = new URL("https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-5.0.2.zip");
        URLConnection connection = url.openConnection();
        int len = connection.getContentLength();
        assertEquals(350192278L, len);
    }
```

**Comment by SunnySourabh** [comment]
> @SunnySourabh ah .. i think you can delete maven-toolchains-plugin in all pom.xml files..
> 
> and this test should work, if there is no issue with the network connection:
> 
> ```
>     @Test
>     public void justCheckIfConnectionIsPossible() throws IOException {
>         URL url = new URL("https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-5.0.2.zip");
>         URLConnection connection = url.openConnection();
>         int len = connection.getContentLength();
>         assertEquals(350192278L, len);
>     }
> ```

@michaelmosmann 
After deleting maven-toolchain pluggin build without test is successful but test are getting failed and the same error I am facing which I was getting in my own project.


java.lang.IllegalStateException: Failed to load ApplicationContext

	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener.prepareTestInstance(SpringBootDependencyInjectionTestExecutionListener.java:43)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:248)
	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:138)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$8(ClassBasedTestDescriptor.java:363)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.executeAndMaskThrowable(ClassBasedTestDescriptor.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$9(ClassBasedTestDescriptor.java:363)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstancePostProcessors(ClassBasedTestDescriptor.java:362)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$instantiateAndPostProcessTestInstance$6(ClassBasedTestDescriptor.java:283)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:282)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:272)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:271)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:102)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:101)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncClientServerWrapper' defined in class path resource [de/flapdoodle/embed/mongo/spring/autoconfigure/EmbeddedMongoAutoConfiguration$SyncClientServerWrapperConfig.class]: Invocation of init method failed; nested exception is java.lang.RuntimeException: error on transition to State(de.flapdoodle.embed.process.types.Archive), rollback
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:136)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	... 72 more
Caused by: java.lang.RuntimeException: error on transition to State(de.flapdoodle.embed.process.types.Archive), rollback
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:174)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:69)
	at de.flapdoodle.embed.mongo.spring.autoconfigure.MongodWrapper.start(MongodWrapper.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1930)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1872)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 87 more
Caused by: java.lang.IllegalStateException: could not download https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-3.3.1.zip
	at de.flapdoodle.embed.process.transitions.DownloadPackage.lambda$result$4(DownloadPackage.java:145)
	at de.flapdoodle.types.ThrowingRunnable.lambda$mapException$0(ThrowingRunnable.java:33)
	at de.flapdoodle.embed.process.transitions.DownloadPackage.result(DownloadPackage.java:146)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:62)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:50)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:165)
	... 96 more
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2048)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2043)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2042)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1609)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at de.flapdoodle.net.URLConnections.downloadAndCopy(URLConnections.java:112)
	at de.flapdoodle.net.URLConnections.downloadIntoTempFile(URLConnections.java:93)
	at de.flapdoodle.net.URLConnections.lambda$downloadIntoFile$3(URLConnections.java:82)
	at de.flapdoodle.net.URLConnections.downloadTo(URLConnections.java:105)
	at de.flapdoodle.net.URLConnections.downloadIntoFile(URLConnections.java:82)
	at de.flapdoodle.embed.process.net.UrlStreams.downloadTo(UrlStreams.java:52)
	at de.flapdoodle.embed.process.net.UrlStreams$Adapter.download(UrlStreams.java:43)
	at de.flapdoodle.embed.process.transitions.DownloadPackage.lambda$result$3(DownloadPackage.java:134)
	at de.flapdoodle.types.ThrowingRunnable.lambda$mapException$0(ThrowingRunnable.java:28)
	... 100 more
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3221)
	at java.base/java.net.URLConnection.getHeaderFieldLong(URLConnection.java:637)
	at java.base/java.net.URLConnection.getContentLengthLong(URLConnection.java:509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLengthLong(HttpsURLConnectionImpl.java:372)
	at de.flapdoodle.net.URLConnections.downloadAndCopy(URLConnections.java:110)
	... 108 more

**Comment by michaelmosmann** [comment]
@SunnySourabh and this small unit test did not run?

.. i can add some logging which may give an hint where to put the downloaded archive .. but this will only fix the download issue.. if any java process can not connect to the url then there is something else .. 

i wounder if your spring-2.x version of this project still works if you move the archive out of the old win32 folder (don't delete:))

**Comment by SunnySourabh** [comment]
> @SunnySourabh are you working in some corporate environment or home office internet connection?

@michaelmosmann 
Working remotely using vpn.

**Comment by michaelmosmann** [comment]
@SunnySourabh maybe disable vpn/proxy .. start test.. see if download is successful, enable vpn?

**Comment by michaelmosmann** [comment]
@SunnySourabh .. could you solve this problem?

**Comment by michaelmosmann** [comment]
@SunnySourabh i created a new release where if there is a connection problem the exception will give a hint where to store a manually downloaded archive to make it work.. 

so reopen if you still have a problem that i can fix somehow:)
