### ISSUE TITLE
Not working with Mac M1

### ISSUE THREAD

**Issue by ShuuutUpandDance** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#20]
Got error:
```
Caused by: java.lang.IllegalArgumentException: osx distribution not supported: GenericFeatureAwareVersion{4.6.2}:Platform{operatingSystem=OS_X, architecture=ARM_64}
	at de.flapdoodle.embed.mongo.packageresolver.PackageFinder$FailWithMessage.packageFor(PackageFinder.java:41)
	at de.flapdoodle.embed.mongo.packageresolver.PackageFinderRules.packageFor(PackageFinderRules.java:45)
	at de.flapdoodle.embed.mongo.packageresolver.OSXPackageFinder.packageFor(OSXPackageFinder.java:50)
	at de.flapdoodle.embed.mongo.packageresolver.PackageFinderRules.packageFor(PackageFinderRules.java:45)
	at de.flapdoodle.embed.mongo.packageresolver.PlatformPackageResolver.packageFor(PlatformPackageResolver.java:58)
	at de.flapdoodle.embed.mongo.transitions.PackageOfCommandDistribution.packageOf(PackageOfCommandDistribution.java:53)
	at de.flapdoodle.embed.mongo.transitions.PackageOfCommandDistribution.result(PackageOfCommandDistribution.java:88)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:62)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:50)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:165)
```

The pom:
```
<dependency>
      <groupId>de.flapdoodle.embed</groupId>
      <artifactId>de.flapdoodle.embed.mongo</artifactId>
      <version>4.6.2</version>
      <scope>test</scope>
  </dependency>
  <dependency>
      <groupId>de.flapdoodle.embed</groupId>
      <artifactId>de.flapdoodle.embed.mongo.spring30x</artifactId>
      <version>4.6.2</version>
      <scope>test</scope>
  </dependency>
```

**Comment by ShuuutUpandDance** [comment]
workable after setting application property `de.flapdoodle.mongodb.embedded.version=3.6.1`

the property was `de.flapdoodle.mongodb.embedded.version=4.6.2` which is not working

**Comment by michaelmosmann** [comment]
@ShuuutUpandDance the version of this dependency does NOT correlate with the version of the mongodb server.. you should use any valid version you can find here: https://www.mongodb.com/try/download/community .. the latests version is 6.0.5
